# Generated by Django 5.0.6 on 2024-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_todolistmdl'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmdl',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolistmdl',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
