# Generated by Django 5.0.6 on 2024-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_todolistmdl_date_todolistmdl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmdl',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
